FROM continuumio/miniconda3
SHELL ["/bin/bash", "-c"]

RUN apt update 
RUN apt install vim -y

COPY .docker/environment.yml .
RUN conda env create --file environment.yml

RUN useradd -m math
USER math

COPY .docker/.bashrc /home/math/.bashrc
ENV PATH "/opt/conda/envs/math/bin:$PATH"
